name: Deploy to Fly
on:
  push:
    branches:
      - main
jobs:
  deploy:
    name: Deploy
    runs-on: ubuntu-latest
    steps:
      # This step checks out a copy of your repository.
      - uses: actions/checkout@v2
      # This step runs `flyctl deploy`.
      - uses: superfly/flyctl-actions@master
        env:
          FLY_API_TOKEN: ${{ secrets.FLY_API_TOKEN }}
        with:
          args: "deploy"
      - uses: rjstone/discord-webhook-notify@v1
        if: success()
        with:
          severity: info
          details: Deployed to fly!
          webhookUrl: ${{ secrets.DISCORD_WEBHOOK }}
      - uses: rjstone/discord-webhook-notify@v1
        if: failure()
        with:
          severity: error
          details: Failed to deploy, see flyctl logs for more info
          webhookUrl: ${{ secrets.DISCORD_WEBHOOK }}
